version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./code:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: fastify
    networks:
      - my-network  
    command: >
      sh -c "
       npm run dev
      " 

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: fastify
    networks:
      - my-network   
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  my-network:
    driver: bridge

volumes:
  pgdata:
